"""Export a case summary as a downloadable PDF using fpdf2 (lightweight, pure-Python,
no system dependencies — unlike reportlab/weasyprint it needs nothing extra installed)."""
from fpdf import FPDF
from datetime import datetime


def build_summary_pdf(filename: str, summary_text: str, language: str, output_path: str):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 12, "LegalSaathi — Case Summary", ln=True)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Document: {filename}", ln=True)
    pdf.cell(0, 8, f"Language: {language}   |   Generated: {datetime.utcnow().strftime('%d %b %Y')}", ln=True)
    pdf.ln(4)

    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "", 12)
    # encode/decode to strip characters fpdf's core fonts can't render (e.g. non-Latin scripts)
    safe_text = summary_text.encode("latin-1", "replace").decode("latin-1")
    pdf.multi_cell(0, 7, safe_text)

    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(140, 140, 140)
    pdf.multi_cell(0, 6, "Generated by LegalSaathi. AI-generated summary — verify against the original document before relying on it.")

    pdf.output(output_path)
    return output_path
